---
abstract: 'Catmandu modules for working with PICA+ data.'
author:
  - 'Johann Rolschewski <rolschewski@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
conflicts:
  Catmandu::SRU: '< 0.032'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-PICA
recommends:
  Catmandu::SRU: '0.032'
requires:
  Catmandu: '0.9'
  XML::LibXML: '1.78'
resources:
  bugtracker: https://github.com/gbv/Catmandu-PICA/issues
  homepage: https://github.com/gbv/Catmandu-PICA
  repository: https://github.com/gbv/Catmandu-PICA.git
version: '0.13'
