---
abstract: 'Catmandu modules for working with PICA+ data.'
author:
  - 'Johann Rolschewski <rolschewski@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
conflicts:
  Catmandu::SRU: '< 0.032'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-PICA
recommends:
  Catmandu::SRU: 0.032
requires:
  Catmandu: 0.7
  XML::LibXML::Reader: 2.0
resources:
  bugtracker: https://github.com/gbv/Catmandu-PICA/issues
  homepage: https://github.com/gbv/Catmandu-PICA
  repository: https://github.com/gbv/Catmandu-PICA.git
version: 0.08
